INSERT INTO university (name, is_active)
VALUES
    ('홍익대학교', true),
    ('인하대학교', true),
    ('상명대학교', true),
    ('숙명여자대학교', true),
    ('중앙대학교', true),
    ('숭실대학교', true),
    ('가천대학교', true),
    ('한양대 ERICA', true),
    ('명지대학교', true),
    ('광운대학교', true),
    ('서경대학교', true),
    ('성신여자대학교', true),
    ('한성대학교', true),
    ('서울여자대학교', true),
    ('이화여자대학교', true),
    ('가톨릭대학교', true),
    ('한국항공대학교', true),
    ('한국외국어대학교', true),
    ('동국대학교', true),
    ('동덕여자대학교', true),
    ('덕성여자대학교', true),
    ('전북대학교', true);
